package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockDao;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemStockDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int insert(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int insertSelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    ItemStockDao selectByPrimaryKey(Integer id);

    ItemStockDao selectByItemId(Integer itemId);

    int decreaseStock(@Param("itemId")Integer itemId, @Param("amount")Integer amount);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int updateByPrimaryKey(ItemStockDao record);
}