package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDao;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ItemDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    List<ItemDao> listItem();
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int insert(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int insertSelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    ItemDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Jul 15 15:02:53 CST 2019
     */
    int updateByPrimaryKey(ItemDao record);

    int increaseSales(@Param("id")Integer itemId, @Param("amount")Integer amount);
}