package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserPasswordDao;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPasswordDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 12 00:27:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 12 00:27:56 CST 2019
     */
    int insert(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 12 00:27:56 CST 2019
     */
    int insertSelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 12 00:27:56 CST 2019
     */
    UserPasswordDao selectByPrimaryKey(Integer id);
    UserPasswordDao selectByUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 12 00:27:56 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 12 00:27:56 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDao record);
}